# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0268bbf5978d3f11241e2f7c62998eba4574a1d756d34420819148e61f824871d1a32b258a46f737faa8d570d091a4b200b1f7215921b80b2d47c7860ee81b4c

test:
  secret_key_base: 9768ee9910255895ded0bc99afd57e0b5687157893fa09de72ec87bef06b147fb78e7e69f21c79b02c0875fc89940bea22b83ed8f37910d1674ff36cfd33d8cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
